#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$BRANCH" != *"chore/ts-definitions-timestamp-"* ]]; then
  yarn commit 
fi

if [[ `git status --porcelain` ]]; then
  git add . && git commit -m 'chore: pre-push fixes'
fi

